name: Update User Agents

on:
  schedule:
    # Run every day at 12:00 UTC (you can adjust this)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'scraper.py'
      - '.github/workflows/update-useragents.yml'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run scraper
      run: python scraper.py
    
    - name: Check for changes
      id: check_changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes
        if git diff --quiet && git diff --cached --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git add .
        git commit -m "Update user agents - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        git push
    
    - name: Create summary
      run: |
        echo "# User Agent Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Date:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ✅ Completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "common/desktop.json" ]; then
          desktop_count=$(python -c "import json; print(json.load(open('common/desktop.json'))['count'])")
          echo "- **Desktop User Agents:** $desktop_count" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -f "common/mobile.json" ]; then
          mobile_count=$(python -c "import json; print(json.load(open('common/mobile.json'))['count'])")
          echo "- **Mobile User Agents:** $mobile_count" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files Updated:" >> $GITHUB_STEP_SUMMARY
        find . -name "*.json" -type f -exec echo "- {}" \; | sort >> $GITHUB_STEP_SUMMARY